services:
  triage-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production-rag-it-security-triage-api
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - EMBEDDING_MODEL_NAME=sentence-transformers/all-MiniLM-L6-v2
      - DOCS_PATH=data/docs
    volumes:
      - ./data/log:/app/data/log

  streamlit-dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: production-rag-it-security-triage-dashboard
    ports:
      - "8501:8501"
    environment:
      - API_BASE_URL=http://triage-api:8000
    command: streamlit run frontend/streamlit_app.py --server.address 0.0.0.0 --server.port 8501
    depends_on:
      - triage-api